name: .NET 8 Build
on:
  push:
    branches:
    - main
env:
  DOTNET_CORE_VERSION: 8.0.100
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          include-prerelease: True
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Install dependencies
        run: dotnet restore 
      - name: Build
        run: dotnet build  --configuration Release --no-restore
      - name: Test
        run: dotnet test  --no-restore --verbosity normal
